In [1]:
import pandas as pd
import numpy as np
import copy
from sklearn import neighbors

In [2]:
aa = pd.read_csv("./3153955.csv")
aa.shape

(3285000, 38)

In [3]:
aa

STATION                     NAME  LATITUDE  LONGITUDE  ELEVATION  \
0        USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
1        USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
2        USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
3        USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
4        USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
...              ...                      ...       ...        ...        ...   
3284995  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   
3284996  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   
3284997  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   
3284998  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   
3284999  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   

                   DATE  HLY-DEWP-NORMAL meas_flag_HLY-DEWP-NORMAL  \
0        01-01T00:00:00             48.2                             
1        01-01T01:00:00             47.9                             
2        01-01T02:00:00             47.6                             
3        01-01T03:00:00             47.4                             
4        01-01T04:00:00             47.1                             
...                 ...              ...                       ...   
3284995  12-31T19:00:00             53.0                             
3284996  12-31T20:00:00             53.1                             
3284997  12-31T21:00:00             53.1                             
3284998  12-31T22:00:00             53.1                             
3284999  12-31T23:00:00             52.6                             

        comp_flag_HLY-DEWP-NORMAL  years_HLY-DEWP-NORMAL  ...  comp_flag_day  \
0                               S                     30  ...            NaN   
1                               S                     30  ...            NaN   
2                               S                     30  ...            NaN   
3                               S                     30  ...            NaN   
4                               S                     30  ...            NaN   
...                           ...                    ...  ...            ...   
3284995                         S                     29  ...            NaN   
3284996                         S                     30  ...            NaN   
3284997                         S                     30  ...            NaN   
3284998                         S                     30  ...            NaN   
3284999                         S                     30  ...            NaN   

        years_day hour  meas_flag_hour  comp_flag_hour years_hour month  \
0             NaN    0             NaN             NaN        NaN     1   
1             NaN    1             NaN             NaN        NaN     1   
2             NaN    2             NaN             NaN        NaN     1   
3             NaN    3             NaN             NaN        NaN     1   
4             NaN    4             NaN             NaN        NaN     1   
...           ...  ...             ...             ...        ...   ...   
3284995       NaN   19             NaN             NaN        NaN    12   
3284996       NaN   20             NaN             NaN        NaN    12   
3284997       NaN   21             NaN             NaN        NaN    12   
3284998       NaN   22             NaN             NaN        NaN    12   
3284999       NaN   23             NaN             NaN        NaN    12   

         meas_flag_month  comp_flag_month years_month  
0                    NaN              NaN         NaN  
1                    NaN              NaN         NaN  
2                    NaN              NaN         NaN  
3                    NaN              NaN         NaN  
4                    NaN              NaN         NaN  
.

In [4]:
aa.columns

Index(['STATION', 'NAME', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'DATE',
       'HLY-DEWP-NORMAL', 'meas_flag_HLY-DEWP-NORMAL',
       'comp_flag_HLY-DEWP-NORMAL', 'years_HLY-DEWP-NORMAL', 'HLY-HIDX-NORMAL',
       'meas_flag_HLY-HIDX-NORMAL', 'comp_flag_HLY-HIDX-NORMAL',
       'years_HLY-HIDX-NORMAL', 'HLY-TEMP-NORMAL', 'meas_flag_HLY-TEMP-NORMAL',
       'comp_flag_HLY-TEMP-NORMAL', 'years_HLY-TEMP-NORMAL', 'HLY-WIND-AVGSPD',
       'meas_flag_HLY-WIND-AVGSPD', 'comp_flag_HLY-WIND-AVGSPD',
       'years_HLY-WIND-AVGSPD', 'HLY-WIND-VCTSPD', 'meas_flag_HLY-WIND-VCTSPD',
       'comp_flag_HLY-WIND-VCTSPD', 'years_HLY-WIND-VCTSPD', 'day',
       'meas_flag_day', 'comp_flag_day', 'years_day', 'hour', 'meas_flag_hour',
       'comp_flag_hour', 'years_hour', 'month', 'meas_flag_month',
       'comp_flag_month', 'years_month'],
      dtype='object')

In [5]:
bb = aa.loc[:][['STATION', 'NAME', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'DATE', 'HLY-DEWP-NORMAL', 'HLY-TEMP-NORMAL', 'HLY-WIND-AVGSPD', 'HLY-WIND-VCTSPD', 'day', 'hour', 'month']]
bb

STATION                     NAME  LATITUDE  LONGITUDE  ELEVATION  \
0        USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
1        USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
2        USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
3        USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
4        USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
...              ...                      ...       ...        ...        ...   
3284995  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   
3284996  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   
3284997  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   
3284998  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   
3284999  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   

                   DATE  HLY-DEWP-NORMAL  HLY-TEMP-NORMAL  HLY-WIND-AVGSPD  \
0        01-01T00:00:00             48.2             56.0              7.6   
1        01-01T01:00:00             47.9             55.4              7.4   
2        01-01T02:00:00             47.6             54.8              7.5   
3        01-01T03:00:00             47.4             54.4              7.8   
4        01-01T04:00:00             47.1             53.8              7.8   
...                 ...              ...              ...              ...   
3284995  12-31T19:00:00             53.0             62.2              6.2   
3284996  12-31T20:00:00             53.1             61.2              6.5   
3284997  12-31T21:00:00             53.1             60.1              6.4   
3284998  12-31T22:00:00             53.1             59.2              5.7   
3284999  12-31T23:00:00             52.6             58.4              5.7   

         HLY-WIND-VCTSPD  day  hour  month  
0                    2.8    1     0      1  
1                    2.9    1     1      1  
2                    3.0    1     2      1  
3                    3.6    1     3      1  
4                    3.7    1     4      1  
...                  ...  ...   ...    ...  
3284995              2.0   31    19     12  
3284996              2.4   31    20     12  
3284997              2.1   31    21     12  
3284998              2.1   31    22     12  
3284999              1.9   31    23     12  

[3285000 rows x 13 columns]

In [6]:
for i in range(1, 13):
    if i == 3:
        continue
        
    filt = bb[bb['month'] == i].index
    bb.drop(filt, inplace = True)
    print(bb.shape)
bb

(3006000, 13)
(2754000, 13)
(2484000, 13)
(2205000, 13)
(1935000, 13)
(1656000, 13)
(1377000, 13)
(1107000, 13)
(828000, 13)
(558000, 13)
(279000, 13)


STATION                     NAME  LATITUDE  LONGITUDE  ELEVATION  \
1416     USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
1417     USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
1418     USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
1419     USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
1420     USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
...              ...                      ...       ...        ...        ...   
3278395  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   
3278396  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   
3278397  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   
3278398  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   
3278399  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   

                   DATE  HLY-DEWP-NORMAL  HLY-TEMP-NORMAL  HLY-WIND-AVGSPD  \
1416     03-01T00:00:00             49.8             59.4              7.9   
1417     03-01T01:00:00             49.6             58.6              7.8   
1418     03-01T02:00:00             49.5             58.0              7.4   
1419     03-01T03:00:00             49.3             57.4              7.6   
1420     03-01T04:00:00             48.9             56.6              7.8   
...                 ...              ...              ...              ...   
3278395  03-31T19:00:00             57.0             72.6              8.6   
3278396  03-31T20:00:00             57.3             70.3              8.1   
3278397  03-31T21:00:00             57.7             68.8              7.5   
3278398  03-31T22:00:00             58.1             67.2              6.1   
3278399  03-31T23:00:00             58.4             66.1              5.7   

         HLY-WIND-VCTSPD  day  hour  month  
1416                 1.7    1     0      3  
1417                 1.9    1     1      3  
1418                 2.1    1     2      3  
1419                 2.5    1     3      3  
1420                 2.7    1     4      3  
...                  ...  ...   ...    ...  
3278395              0.5   31    19      3  
3278396              0.8   31    20      3  
3278397              0.7   31    21      3  
3278398              0.5   31    22      3  
3278399              0.6   31    23      3  

[279000 rows x 13 columns]

In [7]:
for i in range(1, 6):
    filt = bb[bb['day'] == i].index
    bb.drop(filt, inplace = True)
    print(bb.shape)

for i in range(26, 32):
    filt = bb[bb['day'] == i].index
    bb.drop(filt, inplace = True)
    print(bb.shape)

bb

(270000, 13)
(261000, 13)
(252000, 13)
(243000, 13)
(234000, 13)
(225000, 13)
(216000, 13)
(207000, 13)
(198000, 13)
(189000, 13)
(180000, 13)


STATION                     NAME  LATITUDE  LONGITUDE  ELEVATION  \
1536     USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
1537     USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
1538     USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
1539     USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
1540     USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
...              ...                      ...       ...        ...        ...   
3278251  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   
3278252  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   
3278253  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   
3278254  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   
3278255  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   

                   DATE  HLY-DEWP-NORMAL  HLY-TEMP-NORMAL  HLY-WIND-AVGSPD  \
1536     03-06T00:00:00             50.0             59.8              7.6   
1537     03-06T01:00:00             49.8             59.0              7.4   
1538     03-06T02:00:00             49.7             58.2              7.0   
1539     03-06T03:00:00             49.5             57.5              7.3   
1540     03-06T04:00:00             49.1             56.7              7.3   
...                 ...              ...              ...              ...   
3278251  03-25T19:00:00             55.7             71.2              8.6   
3278252  03-25T20:00:00             56.1             69.1              8.0   
3278253  03-25T21:00:00             56.5             67.5              7.4   
3278254  03-25T22:00:00             56.9             65.9              6.4   
3278255  03-25T23:00:00             57.1             64.8              5.8   

         HLY-WIND-VCTSPD  day  hour  month  
1536                 1.3    6     0      3  
1537                 1.5    6     1      3  
1538                 1.7    6     2      3  
1539                 2.2    6     3      3  
1540                 2.3    6     4      3  
...                  ...  ...   ...    ...  
3278251              0.4   25    19      3  
3278252              0.8   25    20      3  
3278253              1.0   25    21      3  
3278254              0.8   25    22      3  
3278255              0.6   25    23      3  

[180000 rows x 13 columns]

In [8]:
zz = ['USW00063862', 'USW00063899', 'USW00063896', 'USW00023801', 'USW00093784', 'USW00063856', 'USW00063855', 'USW00063857', 'USW00063867', 'USW00063838', 'USW00063850', 'USW00063849', 'USW00092821', 'USW00092827', 'USW00092826', 'USW00063898', 'USW00063897', 'USW00064758', 'USW00064756', 'USW00063891', 'USW00003728', 'USW00003733', 'USW00003739', 'USW00053878', 'USW00053877', 'USW00003759', 'USW00003758', 'USW00054794', 'USW00054795', 'USW00054796', 'USW00054797', 'USW00003761', 'USW00063826', 'USW00063829', 'USW00063828']
for i in zz:
    filt = bb[bb['STATION'] == i].index
    bb.drop(filt, inplace = True)
    print(bb.shape)
bb

(179520, 13)
(179040, 13)
(178560, 13)
(178080, 13)
(177600, 13)
(177120, 13)
(176640, 13)
(176160, 13)
(175680, 13)
(175200, 13)
(174720, 13)
(174240, 13)
(173760, 13)
(173280, 13)
(172800, 13)
(172320, 13)
(171840, 13)
(171360, 13)
(170880, 13)
(170400, 13)
(169920, 13)
(169440, 13)
(168960, 13)
(168480, 13)
(168000, 13)
(167520, 13)
(167040, 13)
(166560, 13)
(166080, 13)
(165600, 13)
(165120, 13)
(164640, 13)
(164160, 13)
(163680, 13)
(163200, 13)


STATION                     NAME  LATITUDE  LONGITUDE  ELEVATION  \
1536     USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
1537     USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
1538     USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
1539     USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
1540     USW00093837  JACKSONVILLE NAS, FL US   30.2333   -81.6667        6.1   
...              ...                      ...       ...        ...        ...   
3278251  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   
3278252  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   
3278253  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   
3278254  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   
3278255  USW00012819  LEESBURG MUNI AP, FL US   28.8208   -81.8097       23.5   

                   DATE  HLY-DEWP-NORMAL  HLY-TEMP-NORMAL  HLY-WIND-AVGSPD  \
1536     03-06T00:00:00             50.0             59.8              7.6   
1537     03-06T01:00:00             49.8             59.0              7.4   
1538     03-06T02:00:00             49.7             58.2              7.0   
1539     03-06T03:00:00             49.5             57.5              7.3   
1540     03-06T04:00:00             49.1             56.7              7.3   
...                 ...              ...              ...              ...   
3278251  03-25T19:00:00             55.7             71.2              8.6   
3278252  03-25T20:00:00             56.1             69.1              8.0   
3278253  03-25T21:00:00             56.5             67.5              7.4   
3278254  03-25T22:00:00             56.9             65.9              6.4   
3278255  03-25T23:00:00             57.1             64.8              5.8   

         HLY-WIND-VCTSPD  day  hour  month  
1536                 1.3    6     0      3  
1537                 1.5    6     1      3  
1538                 1.7    6     2      3  
1539                 2.2    6     3      3  
1540                 2.3    6     4      3  
...                  ...  ...   ...    ...  
3278251              0.4   25    19      3  
3278252              0.8   25    20      3  
3278253              1.0   25    21      3  
3278254              0.8   25    22      3  
3278255              0.6   25    23      3  

[163200 rows x 13 columns]

In [9]:
cc = pd.Index.value_counts(bb.loc[:]['STATION'])
cc  # 현재 노드 375개, 시간 480시간

USW00093837    480
USW00013889    480
USW00014752    480
USW00014753    480
USW00013786    480
              ... 
USW00003810    480
USW00013849    480
USW00053870    480
USW00013728    480
USW00012819    480
Name: STATION, Length: 340, dtype: int64

In [10]:
cc = bb.copy()  # 일단 node index 만들기

In [11]:
for i in range(340):
    cc.drop(cc.iloc[i+1:i+480].index, inplace = True)
    print(cc.shape)
cc

(162721, 13)
(162242, 13)
(161763, 13)
(161284, 13)
(160805, 13)
(160326, 13)
(159847, 13)
(159368, 13)
(158889, 13)
(158410, 13)
(157931, 13)
(157452, 13)
(156973, 13)
(156494, 13)
(156015, 13)
(155536, 13)
(155057, 13)
(154578, 13)
(154099, 13)
(153620, 13)
(153141, 13)
(152662, 13)
(152183, 13)
(151704, 13)
(151225, 13)
(150746, 13)
(150267, 13)
(149788, 13)
(149309, 13)
(148830, 13)
(148351, 13)
(147872, 13)
(147393, 13)
(146914, 13)
(146435, 13)
(145956, 13)
(145477, 13)
(144998, 13)
(144519, 13)
(144040, 13)
(143561, 13)
(143082, 13)
(142603, 13)
(142124, 13)
(141645, 13)
(141166, 13)
(140687, 13)
(140208, 13)
(139729, 13)
(139250, 13)
(138771, 13)
(138292, 13)
(137813, 13)
(137334, 13)
(136855, 13)
(136376, 13)
(135897, 13)
(135418, 13)
(134939, 13)
(134460, 13)
(133981, 13)
(133502, 13)
(133023, 13)
(132544, 13)
(132065, 13)
(131586, 13)
(131107, 13)
(130628, 13)
(130149, 13)
(129670, 13)
(129191, 13)
(128712, 13)
(128233, 13)
(127754, 13)
(127275, 13)
(126796, 13)
(126317, 13)

STATION                                NAME  LATITUDE  LONGITUDE  \
1536     USW00093837             JACKSONVILLE NAS, FL US   30.2333   -81.6667   
10296    USW00053819                      ATLANTA, GA US   33.3633   -84.5658   
19056    USW00093718              N MYRTLE BCH AP, SC US   33.8117   -78.7239   
27816    USW00093719        NEW BERN CRAVEN CO AP, NC US   35.0678   -77.0481   
36576    USW00012832              APALACHICOLA AP, FL US   29.7333   -85.0333   
...              ...                                 ...       ...        ...   
3242736  USW00054778                  PENN YAN AP, NY US   42.6425   -77.0564   
3251496  USW00054779          ANDOVER AEROFLEX AP, NJ US   41.0089   -74.7367   
3260256  USW00012816          GAINESVILLE RGNL AP, FL US   29.6919   -82.2756   
3269016  USW00012812  PUNTA GORDA CHARLOTTE CO AP, FL US   26.9172   -81.9914   
3277776  USW00012819             LEESBURG MUNI AP, FL US   28.8208   -81.8097   

         ELEVATION            DATE  HLY-DEWP-NORMAL  HLY-TEMP-NORMAL  \
1536           6.1  03-06T00:00:00             50.0             59.8   
10296        261.5  03-06T00:00:00             39.0             46.9   
19056          9.8  03-06T00:00:00             42.7             49.3   
27816          5.8  03-06T00:00:00             39.1             46.2   
36576          5.8  03-06T00:00:00             50.4             55.7   
...            ...             ...              ...              ...   
3242736      275.2  03-06T00:00:00             20.1             29.3   
3251496      177.7  03-06T00:00:00             22.4             31.8   
3260256       37.5  03-06T00:00:00             48.8             54.8   
3269016        7.6  03-06T00:00:00             55.4             60.6   
3277776       23.5  03-06T00:00:00             52.9             60.0   

         HLY-WIND-AVGSPD  HLY-WIND-VCTSPD  day  hour  month  
1536                 7.6              1.3    6     0      3  
10296                3.3              1.1    6     0      3  
19056                6.2              1.5    6     0      3  
27816                5.4              1.2    6     0      3  
36576                5.7              0.7    6     0      3  
...                  ...              ...  ...   ...    ...  
3242736              7.5              4.4    6     0      3  
3251496              3.5              1.2    6     0      3  
3260256              4.2              0.8    6     0      3  
3269016              6.1              2.3    6     0      3  
3277776              5.3              0.5    6     0      3  

[340 rows x 13 columns]

In [12]:
dd = pd.Index.value_counts(cc.loc[:]['STATION'])
dd

USW00093837    1
USW00013889    1
USW00014752    1
USW00014753    1
USW00013786    1
              ..
USW00003810    1
USW00013849    1
USW00053870    1
USW00013728    1
USW00012819    1
Name: STATION, Length: 340, dtype: int64

In [13]:
cc['ELEVATION'] *= 0.0001  # 높이 차이를 좀 줄이장
dd = np.array(cc.loc[:][['LATITUDE', 'LONGITUDE', 'ELEVATION']])
dd.shape, dd

((340, 3),
 array([[ 3.02333e+01, -8.16667e+01,  6.10000e-04],
        [ 3.33633e+01, -8.45658e+01,  2.61500e-02],
        [ 3.38117e+01, -7.87239e+01,  9.80000e-04],
        ...,
        [ 2.96919e+01, -8.22756e+01,  3.75000e-03],
        [ 2.69172e+01, -8.19914e+01,  7.60000e-04],
        [ 2.88208e+01, -8.18097e+01,  2.35000e-03]]))

In [33]:
nbrs = neighbors.NearestNeighbors(n_neighbors=7, radius = 1.377, algorithm='brute').fit(dd)
distance, indice = nbrs.radius_neighbors(dd)

In [34]:
indice

array([array([  0,  33,  76, 137, 199, 219, 224, 337], dtype=int64),
       array([  1,  23,  56,  84, 102, 103, 119, 125, 128, 138, 161, 163, 168,
              296], dtype=int64)                                              ,
       array([  2,  40,  52, 123, 177, 206, 324], dtype=int64),
       array([  3,  12,  83, 160, 177, 269, 300], dtype=int64),
       array([  4,  85, 114, 133], dtype=int64),
       array([  5,  60,  72, 152, 181, 254], dtype=int64),
       array([  6,  25,  49,  50,  97,  99, 132, 147, 228, 240], dtype=int64),
       array([  7,  21,  24,  43,  73,  75, 114, 133, 145, 153, 159, 165, 189,
              200, 203, 209, 214, 216, 259], dtype=int64)                     ,
       array([  8,  32,  85, 137, 149, 172, 176], dtype=int64),
       array([  9,  77, 113, 119, 143, 163, 174, 185, 236, 263], dtype=int64),
       array([ 10, 107, 157], dtype=int64),
       array([ 11, 112, 124, 139, 167, 178, 197, 244, 304, 323], dtype=int64),
       array([  3,  12,  83, 160

In [35]:
for i in indice:
    if len(i) == 1:
        print("beep")

In [36]:
distance[210]

array([1.37632466, 0.        ])

In [37]:
for i in range(340):
    if len(indice[i]) == 1:
        print(i)

In [38]:
for i in range(len(distance)):
    if len(distance[i]) < 6:
        continue
    else:
        while len(distance[i]) > 6:
#             print(distance[i])
            kk = np.where(distance[i] == max(distance[i]))
            distance[i] = np.delete(distance[i], kk)
            indice[i] = np.delete(indice[i], kk)
#     a = np.where(distance[i] > 3.)
#     print(a)  # len(distance[i] - len(a)) 7 - 5 = 2
#     print(len(distances[i]) - len(a[0]))
#     distances[i] = distances[i][~np.isin(np.arange(distances[i].size), a)]

In [39]:
ind1 = []
ind2 = []
for i in range(len(indice)):
    new_ind1 = [i]*(len(indice[i])-1)
    new_ind2 = []
    for j in range(len(indice[i])):
        if indice[i][j] != i:
            new_ind2 += [indice[i][j]]
    ind1 += new_ind1
    ind2 += new_ind2
print(len(ind1), len(ind2))

1623 1623


In [40]:
indice

array([array([  0,  76, 199, 219, 224, 337], dtype=int64),
       array([  1, 102, 103, 128, 161, 296], dtype=int64),
       array([  2,  52, 123, 177, 206, 324], dtype=int64),
       array([  3,  12,  83, 160, 269, 300], dtype=int64),
       array([  4,  85, 114, 133], dtype=int64),
       array([  5,  60,  72, 152, 181, 254], dtype=int64),
       array([  6,  25,  49,  99, 147, 240], dtype=int64),
       array([  7, 145, 165, 189, 200, 214], dtype=int64),
       array([  8,  32,  85, 137, 149, 172], dtype=int64),
       array([  9, 163, 174, 185, 236, 263], dtype=int64),
       array([ 10, 107, 157], dtype=int64),
       array([ 11, 112, 139, 244, 304, 323], dtype=int64),
       array([  3,  12,  83, 160, 177, 300], dtype=int64),
       array([ 13,  22,  41,  59, 130, 211], dtype=int64),
       array([ 14,  79,  91, 186, 194, 273], dtype=int64),
       array([ 15, 160, 230, 300], dtype=int64),
       array([ 16,  67,  70, 227, 305, 332], dtype=int64),
       array([ 17,  26, 117, 166

In [41]:
ee = np.vstack((ind1, ind2))
ee.shape, ee

((2, 1623),
 array([[  0,   0,   0, ..., 339, 339, 339],
        [ 76, 199, 219, ...,  65, 332, 334]], dtype=int64))

In [42]:
np.save('edge_index_NOAA.npy', ee)

In [43]:
ff = np.random.randint(43, size = (1623,))
ff

array([32, 42, 11, ..., 34, 14, 40])

In [44]:
np.save('edge_attr_NOAA.npy', ff)

In [45]:
ba = np.load('./edge_index_NOAA.npy')
ca = np.load('./edge_attr_NOAA.npy')
ba, ca

(array([[  0,   0,   0, ..., 339, 339, 339],
        [ 76, 199, 219, ...,  65, 332, 334]], dtype=int64),
 array([32, 42, 11, ..., 34, 14, 40]))

# ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

In [132]:
gg = bb.copy()
hh = gg.loc[:][['STATION', 'HLY-TEMP-NORMAL', 'HLY-DEWP-NORMAL', 'HLY-WIND-AVGSPD', 'HLY-WIND-VCTSPD', 'day', 'hour']]
# hh.reset_index(inplace = True)
hh

STATION  HLY-TEMP-NORMAL  HLY-DEWP-NORMAL  HLY-WIND-AVGSPD  \
1536     USW00093837             59.8             50.0              7.6   
1537     USW00093837             59.0             49.8              7.4   
1538     USW00093837             58.2             49.7              7.0   
1539     USW00093837             57.5             49.5              7.3   
1540     USW00093837             56.7             49.1              7.3   
...              ...              ...              ...              ...   
3278251  USW00012819             71.2             55.7              8.6   
3278252  USW00012819             69.1             56.1              8.0   
3278253  USW00012819             67.5             56.5              7.4   
3278254  USW00012819             65.9             56.9              6.4   
3278255  USW00012819             64.8             57.1              5.8   

         HLY-WIND-VCTSPD  day  hour  
1536                 1.3    6     0  
1537                 1.5    6     1  
1538                 1.7    6     2  
1539                 2.2    6     3  
1540                 2.3    6     4  
...                  ...  ...   ...  
3278251              0.4   25    19  
3278252              0.8   25    20  
3278253              1.0   25    21  
3278254              0.8   25    22  
3278255              0.6   25    23  

[163200 rows x 7 columns]

In [133]:
len(np.where(hh.iloc[:,1] == -9999)[0]), len(np.where(hh.iloc[:,2] == -9999)[0]), len(np.where(hh.iloc[:,3] == -9999)[0]), len(np.where(hh.iloc[:,4] == -9999)[0])

(63, 102, 84, 84)

In [134]:
print(np.where(hh.iloc[:,1] == -9999))
print(np.where(hh.iloc[:,1] == -9999)[0])

(array([68660, 68684, 68708, 68732, 68756, 68780, 68804, 68828, 68852,
       68876, 68900, 68924, 68948, 68972, 68996, 69020, 69044, 69068,
       69092, 69116, 72001, 72002, 72003, 72005, 72025, 72026, 72027,
       72029, 72049, 72050, 72051, 72053, 72073, 72074, 72075, 72077,
       72097, 72098, 72099, 72101, 72121, 72122, 72145, 72146, 72147,
       72169, 72170, 72171, 72192, 72193, 72194, 72195, 72216, 72217,
       72218, 72219, 72240, 72241, 72242, 72243, 72265, 72266, 97914],
      dtype=int64),)
[68660 68684 68708 68732 68756 68780 68804 68828 68852 68876 68900 68924
 68948 68972 68996 69020 69044 69068 69092 69116 72001 72002 72003 72005
 72025 72026 72027 72029 72049 72050 72051 72053 72073 72074 72075 72077
 72097 72098 72099 72101 72121 72122 72145 72146 72147 72169 72170 72171
 72192 72193 72194 72195 72216 72217 72218 72219 72240 72241 72242 72243
 72265 72266 97914]


In [135]:
for j in range(1, 5):
    
    for i in np.where(hh.iloc[:,j] == -9999)[0]:
        
        if (hh.iloc[i, 5] == 6) or (hh.iloc[i, 5] == 25) or (hh.iloc[i-1, j] == -9999) or (hh.iloc[i, j] != -9999):
            continue
        
        if hh.iloc[i+1, j] != -9999:
            hh.iloc[i, j] = round((hh.iloc[i-1, j] + hh.iloc[i+1, j])/2, 4)
            
        elif hh.iloc[i+2, j] != -9999:
            hh.iloc[i, j] = round((hh.iloc[i-1, j]*2 + hh.iloc[i+2, j])/3, 4)
            hh.iloc[i+1, j] = round((hh.iloc[i-1, j] + hh.iloc[i+2, j]*2)/3, 4)
            
        elif hh.iloc[i+3, j] != -9999:
            hh.iloc[i, j] = round((hh.iloc[i-1, j]*3 + hh.iloc[i+3, j])/4, 4)
            hh.iloc[i+1, j] = round((hh.iloc[i-1, j]*2 + hh.iloc[i+3, j]*2)/4, 4)
            hh.iloc[i+2, j] = round((hh.iloc[i-1, j] + hh.iloc[i+3, j]*3)/4, 4)
            
        elif hh.iloc[i+4, j] != -9999:
            hh.iloc[i, j] = round((hh.iloc[i-1, j]*4 + hh.iloc[i+4, j])/5, 4)
            hh.iloc[i+1, j] = round((hh.iloc[i-1, j]*3 + hh.iloc[i+4, j]*2)/5, 4)
            hh.iloc[i+2, j] = round((hh.iloc[i-1, j]*2 + hh.iloc[i+4, j]*3)/5, 4)
            hh.iloc[i+3, j] = round((hh.iloc[i-1, j] + hh.iloc[i+4, j]*4)/5, 4)

In [136]:
len(np.where(hh.iloc[:,1] == -9999)[0]), len(np.where(hh.iloc[:,2] == -9999)[0]), len(np.where(hh.iloc[:,3] == -9999)[0]), len(np.where(hh.iloc[:,4] == -9999)[0])

(7, 9, 9, 9)

In [145]:
for i in [6, 25]:
    filt = hh[hh['day'] == i].index  # 146880/340 = 432  이틀만 더 줄이면 댐
    hh.drop(filt, inplace = True)
    print(hh.shape)

len(np.where(hh.iloc[:,1] == -9999)[0]), len(np.where(hh.iloc[:,2] == -9999)[0]), len(np.where(hh.iloc[:,3] == -9999)[0]), len(np.where(hh.iloc[:,4] == -9999)[0]), hh

(155040, 7)
(146880, 7)


(0,
 0,
 0,
 0,
              STATION  HLY-TEMP-NORMAL  HLY-DEWP-NORMAL  HLY-WIND-AVGSPD  \
 1560     USW00093837             60.2             50.3              7.6   
 1561     USW00093837             59.3             50.2              7.4   
 1562     USW00093837             58.6             50.1              7.0   
 1563     USW00093837             57.9             49.9              7.3   
 1564     USW00093837             57.1             49.4              7.1   
 ...              ...              ...              ...              ...   
 3278227  USW00012819             70.9             55.3              8.6   
 3278228  USW00012819             68.9             55.8              8.1   
 3278229  USW00012819             67.2             56.2              7.6   
 3278230  USW00012819             65.7             56.6              6.5   
 3278231  USW00012819             64.6             56.8              5.9   
 
          HLY-WIND-VCTSPD  day  hour  
 1560                 1.3    7 

In [147]:
for i in [23, 24]:
    filt = hh[hh['day'] == i].index  # 130560/340 = 384  7일 00:00 ~ 22일 23:00
    hh.drop(filt, inplace = True)
    print(hh.shape)

(130560, 7)
(130560, 7)


In [154]:
ii = np.array(hh.iloc[:,1:5])
ii.shape, ii

((130560, 4),
 array([[60.2, 50.3,  7.6,  1.3],
        [59.3, 50.2,  7.4,  1.5],
        [58.6, 50.1,  7. ,  1.7],
        ...,
        [66.9, 55.5,  7.5,  1.2],
        [65.4, 56. ,  6.5,  0.9],
        [64.3, 56.2,  5.9,  0.6]]))

In [170]:
jj = np.array([[ii[0]]])
print(jj)

for i in range(1, 340):
    jj = np.concatenate((jj, np.array([[ii[384*i]]])), axis = 1)

print(jj)

for i in range(1, 384):
    kk = np.array([[ii[i]]])
#     print(kk)
    for j in range(1, 340):
        kk = np.concatenate((kk, np.array([[ii[j*384 + i]]])), axis = 1)
    jj = np.concatenate((jj, kk), axis = 0)
jj.shape

[[[60.2 50.3  7.6  1.3]]]
[[[60.2 50.3  7.6  1.3]
  [47.6 39.8  3.4  1. ]
  [49.8 43.3  6.3  1.6]
  ...
  [55.1 49.1  4.1  0.8]
  [60.8 55.5  6.1  2. ]
  [60.3 53.1  5.5  0.4]]]


(384, 340, 4)

In [174]:
pd.DataFrame(jj[0])

0     1    2    3
0    60.2  50.3  7.6  1.3
1    47.6  39.8  3.4  1.0
2    49.8  43.3  6.3  1.6
3    46.9  39.8  5.6  1.2
4    56.1  50.8  5.7  0.5
..    ...   ...  ...  ...
335  30.1  20.7  7.5  4.3
336  32.5  23.1  3.4  1.1
337  55.1  49.1  4.1  0.8
338  60.8  55.5  6.1  2.0
339  60.3  53.1  5.5  0.4

[340 rows x 4 columns]

In [178]:
pd.DataFrame(jj[1])

0     1    2    3
0    59.3  50.2  7.4  1.5
1    47.0  39.5  3.7  1.2
2    49.3  43.1  5.9  1.4
3    46.3  39.5  5.9  1.2
4    55.5  50.4  8.8  4.0
..    ...   ...  ...  ...
335  29.7  20.6  7.8  4.8
336  31.6  23.0  3.2  1.3
337  54.0  48.7  4.1  0.8
338  59.6  55.2  6.0  2.2
339  59.5  53.1  5.2  0.4

[340 rows x 4 columns]

In [182]:
hh.iloc[0, 1:5], hh.iloc[1, 1:5], hh.iloc[384, 1:5], hh.iloc[385, 1:5]  # 검산 끝

(HLY-TEMP-NORMAL    60.2
 HLY-DEWP-NORMAL    50.3
 HLY-WIND-AVGSPD     7.6
 HLY-WIND-VCTSPD     1.3
 Name: 1560, dtype: object,
 HLY-TEMP-NORMAL    59.3
 HLY-DEWP-NORMAL    50.2
 HLY-WIND-AVGSPD     7.4
 HLY-WIND-VCTSPD     1.5
 Name: 1561, dtype: object,
 HLY-TEMP-NORMAL    47.6
 HLY-DEWP-NORMAL    39.8
 HLY-WIND-AVGSPD     3.4
 HLY-WIND-VCTSPD     1.0
 Name: 10320, dtype: object,
 HLY-TEMP-NORMAL    47.0
 HLY-DEWP-NORMAL    39.5
 HLY-WIND-AVGSPD     3.7
 HLY-WIND-VCTSPD     1.2
 Name: 10321, dtype: object)

In [184]:
np.save('./X_NOAA.npy', jj)

In [32]:
ll = np.load('./X_NOAA.npy')
ll.shape, ll

((384, 340, 4),
 array([[[60.2, 50.3,  7.6,  1.3],
         [47.6, 39.8,  3.4,  1. ],
         [49.8, 43.3,  6.3,  1.6],
         ...,
         [55.1, 49.1,  4.1,  0.8],
         [60.8, 55.5,  6.1,  2. ],
         [60.3, 53.1,  5.5,  0.4]],
 
        [[59.3, 50.2,  7.4,  1.5],
         [47. , 39.5,  3.7,  1.2],
         [49.3, 43.1,  5.9,  1.4],
         ...,
         [54. , 48.7,  4.1,  0.8],
         [59.6, 55.2,  6. ,  2.2],
         [59.5, 53.1,  5.2,  0.4]],
 
        [[58.6, 50.1,  7. ,  1.7],
         [46.3, 39.3,  3.8,  1.2],
         [48.7, 42.6,  5.8,  1.3],
         ...,
         [53.1, 48.4,  3.7,  0.7],
         [58.7, 55. ,  5.7,  2.2],
         [58.9, 53. ,  5. ,  0.8]],
 
        ...,
 
        [[66.5, 53.2,  8.4,  1.5],
         [55.5, 44.9,  3.2,  0.6],
         [55.4, 47.8,  7. ,  2. ],
         ...,
         [62.8, 53.1,  6.1,  0.7],
         [67.4, 58.4,  7.2,  1.5],
         [66.9, 55.5,  7.5,  1.2]],
 
        [[65.6, 53.6,  8.1,  1.3],
         [53.8, 44.6,  3.1

In [33]:
np.mean((np.mean(ll, axis = 0)), axis = 0)

array([47.86242839, 34.86508157,  8.07632161,  2.56402612])

In [34]:
mm = ll-np.mean((np.mean(ll, axis = 0)), axis = 0)
ll-np.mean((np.mean(ll, axis = 0)), axis = 0)

array([[[12.33757161, 15.43491843, -0.47632161, -1.26402612],
        [-0.26242839,  4.93491843, -4.67632161, -1.56402612],
        [ 1.93757161,  8.43491843, -1.77632161, -0.96402612],
        ...,
        [ 7.23757161, 14.23491843, -3.97632161, -1.76402612],
        [12.93757161, 20.63491843, -1.97632161, -0.56402612],
        [12.43757161, 18.23491843, -2.57632161, -2.16402612]],

       [[11.43757161, 15.33491843, -0.67632161, -1.06402612],
        [-0.86242839,  4.63491843, -4.37632161, -1.36402612],
        [ 1.43757161,  8.23491843, -2.17632161, -1.16402612],
        ...,
        [ 6.13757161, 13.83491843, -3.97632161, -1.76402612],
        [11.73757161, 20.33491843, -2.07632161, -0.36402612],
        [11.63757161, 18.23491843, -2.87632161, -2.16402612]],

       [[10.73757161, 15.23491843, -1.07632161, -0.86402612],
        [-1.56242839,  4.43491843, -4.27632161, -1.36402612],
        [ 0.83757161,  7.73491843, -2.27632161, -1.26402612],
        ...,
        [ 5.23757161, 13.53

In [35]:
sigma = np.sqrt(np.sum(np.sum(mm**2, axis = 0), axis = 0))
nn = mm/sigma
nn.sum()

-1.1577405700791132e-12

In [36]:
np.save('./X_NOAA(normalize).npy', nn)